### ISSUE TITLE
Are PRs still accepted?? + FUTURE OF THE EEPO

### ISSUE THREAD

**Issue by GabrielTK** [fenix01/cheatengine-library#13]
Hi,
I know this repo is now maintened by the community, but, if I send a PR, will it still be accepted?? (Also, going to send @fenix01 an email regarding the future of this repo)

**Comment by fenix01** [comment]
Hi Gabriel,

Thank you for your interest in this project. To give further informations about this project and the future, I don't plan any updates or bug fixes. I'm very busy and I don't have the time to work on this library during my free time. But I will accept any contributions :)
