### ISSUE TITLE
How to use Pointer

### ISSUE THREAD

**Issue by A-VORONKIN** [fenix01/cheatengine-library#5]
How to use pointer and offsets from Cheat Engine? I want to change value by it.

**Comment by fenix01** [comment]
Hi A-VORONKIN,

Did you try this API IProcessAddress ? You may pass the address of the pointer and this call will read the value pointed by your pointer.

**Comment by A-VORONKIN** [comment]
But how to use offsets with pointer adress? Can you write some example?

**Comment by fenix01** [comment]
Here it's an example I made in c#.
But I think, there is a tip with the IProcessAddress api because it doesn't work. I will try to fix it as soon as possible.

            long baseAddress = 0x3BBAAF0000;
            int offset = 0;
            long pointer = baseAddress + offset;
            string ptr = "$" + pointer.ToString("X16");
            string out_;
            lib.iProcessAddress(ptr, TVariableType.vtDword, false, false, 1, out out_);
            MessageBox.Show(out_);

**Comment by A-VORONKIN** [comment]
It will be greate if we can add pointer and offsets to cheatengine virtual table like it is in Cheat Engine app.

**Comment by fenix01** [comment]
Yes you're right, I will look at this new feature. But I can't promise when it will be available.
I don't have lot of time to work on the library

**Comment by fenix01** [comment]
Hi Voronkin :)

So I made some investigations and I found the solution to the problem. I just made a small mistake in the example.
IProcessAddress will get the current value of an address. So, to read the value pointed you need to make a second call to IProcessAddress.

            long baseAddress = 0xCECB6F0000;
            int offset = 0;
            long pointer = baseAddress + offset;
            string ptrAddress = pointer.ToString("X16");
            string ptrValue;
            lib.iProcessAddress(ptrAddress, TVariableType.vtQword, true, false, 1, out ptrValue);

            string pointedValue;
            lib.iProcessAddress(ptrValue, TVariableType.vtDword, false, false, 1, out pointedValue);
            MessageBox.Show(pointedValue);

**Comment by A-VORONKIN** [comment]
It's working fine, thanks!
